local path = minetest.get_modpath("fac_events")
dofile (path .. "/claim_events.lua")
dofile (path .. "/diplomacy_events.lua")
dofile (path .. "/eventcallbacks.lua")
dofile (path .. "/invite_events.lua")
dofile (path .. "/player_events.lua")
dofile (path .. "/power_events.lua")
dofile (path .. "/rank_events.lua")
